name: "DDNS"
description: "update dns with local machine ips"
version: "0.1.17"
slug: "ddns"
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  id:
  token:
  dns: "dnspod"
  ipv4:
  ipv6:
  index4: "public"
  index6: "default"
  debug: false
  cache: true
schema:
  id: str
  token: str
  dns: str
  ipv4: str
  ipv6: str
  index4: str
  index6: str
  debug: bool
  cache: bool
