# https://github.com/NewFuture/DDNS
name: DDNS
description: 自动更新 DNS 解析 到本机 IP 地址,支持 ipv4 和 ipv6 以 本地(内网)IP 和 公网 IP。 代理模式,支持自动创建域名记录。
url: https://github.com/AlexxIT/hassio-addons/tree/master/ssh_tunnel
arch: [ amd64, aarch64, i386, armv7, armhf ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.0.0
slug: ddns
init: false
startup: system
host_network: true

options:
  id: null
  token: null
  dns: dnspod
  ipv4: []
  ipv6: []
  index4: default
  index6: default
  ttl: null
  proxy: null
  debug: false
  cache: true
schema:
  id: str
  token: str
  dns: str
  ipv4: list
  ipv6: list
  index4: str?
  index6: str?
  ttl: int
  proxy: str?
  debug: bool
  cache: bool